### PR TITLE
Restructure project for better portability

### PR DESCRIPTION
**Pull request by BryceBarbara**
## About

It's time to break up code for engine related things and code for the WorldExplorer app. That's the main thing this does. I came up with "JetBlackEngine" because that's the name of the engine. 🤷‍♂️

## Changes

* Added two new C# projects
    * `JetBlackEngineLib` will now contain engine related code
    * `JetBlackEngineLib.Tests` will contain unit tests
* Moved most engine code into `JetBlackEngineLib`
* Restructured the project namespace layout to group types by feature
* Added basic unit tests for `BdgaAnmDecoder` and `RtaAnmDecoder`
* Added some interfaces that will be used in the future to reduce coupling
* Switched to file scoped namespaces in the solution

**Note:** Some files lost their license headers that they previously had. Since some files were already lacking that, I figured it would be okay. If not, please let me know and I can create a commit that adds them to all files.

### CODE REVIEW

**Comment by BryceBarbara** [comment]
@bigianb It's been a minute. Let me know if you have any issues with this.

**Comment by bigianb** [comment]
where do the 2 anm files come from? If you made them, that's fine but if they're from one of the games then we should not include them because they will be copyrighted by the developer or publisher.

**Comment by BryceBarbara** [comment]
I will delete them from the repo history and recreate some that we can use for testing.

**Comment by BryceBarbara** [comment]
The anim files still existed in the repo so I'll create a new PR for removing them

**Pull request merged**
